#私聊ai开关
isPrivte: false
#私聊ai概率
probability: 0
#私聊ai类型
aiType: 思知
#ai名称
botname: 思知
#示例数据
1212121: #群配置
  #是否群内开启
  isOpen: false
  #设置ai类型 （小爱同学、思知、青云客、gpt(3.5他是这么写的)）
  aiType: 思知
  #设置ai触发概率
  gprobability: 0
