#写一个注释
textapi:
  - url: http://apii.gq/api/renjian.php
    data: 0
    reg: 人间凑数
    name: 人间凑数
  - url: https://v1.hitokoto.cn/
    data: ["hitokoto"]
    reg: 一言
    name: 一言
  - url: http://apii.gq/api/shiju.php
    data: 0
    reg: 古诗名句
    name: 古诗名句
  - url: https://xian.txma.cn/API/yiyan.php
    data: 0
    reg: 名人一言
    name: 名人一言
  - url: https://v.api.aa1.cn/api/api-wenan-ktff/index.php?type=5
    data: 0
    reg: 口吐芬芳
    name: 口吐芬芳
  - url: http://apii.gq/api/shangganyl.php
    data: 0
    reg: 伤感语录
    name: 伤感语录
  - url: https://xiaobai.klizi.cn/API/other/chp.php
    data: 0
    reg: 彩虹屁
    name: 彩虹屁
