monringMsg:  #早安的触发台词
    morn:
      - "早！"
      - "早上好！"
      - " 早起的鸟儿有虫吃，加油!"
      - "早安~"
      - "新的一天又开始了。"
      - "小鸟说早早早，花儿也在对着我欢笑~"
    noon:
      - "太阳都屁股了，你才起来啊~"
      - "大懒猪，哼哼哼哼~"
      - "大懒虫起不来，略略略~"
      - "太懒了，现在才起来！"
    afternoon:
      - "早什么早，都要晚上了。"
      - "早你个头。"
      - "别早安了，我都准备下班回家了"
    night:
      - "我都准备洗洗睡了，还早，哼！"
      - "哈~睡觉。",
      - "不是...你看看几点了，哼！"
    over:
      - "zzz...zzz"
      - "zzz..."
      - "zzzz...涩图...嘿嘿..."
      - "zzz..有猪猪在叫我...zzz"
eveningMsg:
    morn: 
      - "猝死吧你！"
      - "别睡了通宵吧...哼哼哼！"
      - "你还知道睡觉啊!"
    noon: 
      - "睡什么睡，修仙吧~"
      - "不如别睡了，晚安啥~"
    afternoon: 
      - "睡那么早，我才不信。"
      - "哈，这个点睡觉？"
    night: 
      - "呼...呼...已经睡着了哦~呼..."
    over:
      - "zzz...zzz"
      - "zzz..."
      - "zzzz...涩图...嘿嘿..."
      - "zzz..有猪猪在叫我...zzz"
# advice:
#     mintime: 
#       a: "最近是不是修仙了，这明明就算是没睡嘛!"
#       b: "这点时间可不行呢，有什么重要的事才睡这么少呢？"
#       c: "稍微睡了一点，这样可没法撑一天呢,要多注意休息！"
