ai:
  title: ai功能
  set:
    #私聊ai开关
    isPrivte:
      title: "私聊ai" #属性名
      def: false
      type: Boolean
      desc: "私聊是否开启ai"
      reg: "#千羽设置私聊ai开启/关闭"
    #私聊ai概率
    probability:
      title: "私聊ai概率" #属性名
      def: 0
      range: [0, 100]
      type: Number
      desc: "私聊触发的概率"
      reg: "#千羽设置私聊ai概率（0-100）"
    #私聊ai类型
    aiType:
      title: "私聊ai类型" #属性名
      def: 思知
      type: String
      range: [思知, 青云客, 小爱同学, gpt]
      desc: "私聊的ai，可以设置思知、青云客、小爱同学、gpt"
      reg: "#千羽设置私聊ai类型思知"
    botname:
      title: "ai名称" #属性名
      def: 思知
      type: String
      desc: "设置ai名称为任意名称"
      reg: "#千羽设置ai名称思知"
  GroupSet:
    isOpen:
      title: "群聊ai" #属性名
      def: false
      type: Boolean
      desc: "群聊是否开启ai"
      reg: "#千羽设置群聊ai开启/关闭"
    #私聊ai概率
    gprobability:
      title: "群聊ai概率" #属性名
      def: 0
      range: [0, 100]
      type: Number
      desc: "群聊触发的概率"
      reg: "#千羽设置群聊ai概率（0-100）"
    #私聊ai类型
    aiType:
      title: "群聊ai类型" #属性名
      def: 思知
      type: String
      range: [思知, 青云客, 小爱同学, gpt]
      desc: "群聊的ai，可以设置思知、青云客、小爱同学、gpt"
      reg: "#千羽设置群聊ai类型思知"
bilibili:
  title: B站功能
  set:
    card:
      title: b站解析卡片
      def: false
      type: Boolean
      desc: B站解析是否开启卡片信息
      reg: "#千羽设置b站解析卡片开启/关闭"
    isjx:
      title: b站解析
      def: false
      type: Boolean
      desc: B站解析是否开启
      reg: "#千羽设置b站解析开启/关闭"
douyin:
  title: 抖音功能
  set:
    isjx:
      title: 抖音解析
      def: false
      type: Boolean
      desc: 抖音解析是否开启
      reg: "#千羽设置抖音解析开启/关闭"
groupimg:
  title: 群聊学习功能
  set:
    learnTimes:
      title: 表情包学习次数
      def: 10
      range: [1, 100]
      type: Number
      desc: 群聊中表情包重复出现的次数，超过这个次数才进行学习
      reg: "#千羽设置表情包学习次数10"
    isSendMsg:
      title: 表情包学习提醒
      def: false
      type: Boolean
      desc: 每天凌晨发送学习的表情包合集
      reg: "#千羽设置表情包学习提醒开启/关闭"
    random:
      title: 随机表情包概率
      def: 10
      range: [0, 100]
      type: Number
      desc: 触发随机表情包的概率
      reg: "#千羽设置随机表情包概率10"
  GroupSet:
    isOpen:
      title: 群随机表情
      def: false
      type: Boolean
      desc: 发送每天学习的表情包
      reg: "#千羽设置群随机表情开启/关闭"
help:
  title: 帮助功能
  set:
    randomImgOpen:
      title: 随机帮助图背景
      def: false
      type: Boolean
      desc: 设置千羽设置的帮助图是否随机
      reg: "#千羽设置随机帮助图背景开启/关闭"
chuo:
  title: 戳一戳
  set:
    isOpen:
      title: 戳一戳表情
      def: false
      type: Boolean
      desc: 发送每天学习的表情包
      reg: "#千羽设置戳一戳表情开启/关闭"
other:
  title: 其他设置
  set:
    isscreenshot:
      title: 网页截图
      def: true
      type: Boolean
      desc: 检测到网址自动解析
      reg: "#千羽设置网页截图开启/关闭"
system.puppeteer:
  title: 浏览器模式
  set:
    mode:
      title: 浏览器模式
      def: "qianyu"
      type: String
      range: [qianyu, yunzai]
      desc: 截图所选择的浏览器,qianyu为插件功能截图，yunzai为bot原生截图
      reg: "#千羽设置浏览器模式qianyu"
